### ISSUE TITLE
Data revalidated twice ?

### ISSUE THREAD

**Issue by antoinechalifour** [alexanderson1993/remix-live-loader#1]
Hi Alex, thanks for the talk at Remix Conf !

I tried a similar approach (pretty much exactly the same) a few month ago, and it worked really well. Except that the client that did the POST request (running the action) got the data revalidated twice : once because of the action, and once because of the event stream.

Is it the same in your demo ? Do you have a workaround that isn't convoluted (I tried tracking user sessions, giving and ID to each client, ...)

Have a great day

**Comment by alexanderson1993** [comment]
Yeah, I didn't have enough time to talk through those issues. If you've got a good server-side cache (which you should have anyway in this case), it shouldn't be too much of a problem.

If you really wanted to limit it, you'd have to have some kind of identifier for the client, maybe in a cookie. When the client subscribes to SSE, that ID can be used to filter the messages sent to just that client. Then, when the client fires off the action, it includes its ID in the pub/sub payload. In the SSE handler, if the payload ID matches the subscribed client ID, it just doesn't send the message.

There are probably better ways to do it, but this should cover the simplest cases.
